# Generated by Django 2.0 on 2017-12-14 16:40

from django.db import migrations, models
import django.db.models.deletion
import industry.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=True))))), ('pullout', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock()), ('stat', wagtail.core.blocks.CharBlock())))), ('content', wagtail.core.blocks.TextBlock()), ('snippet', wagtail.snippets.blocks.SnippetChooserBlock(target_model=industry.models.StaticContent))))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
