# Generated by Django 2.0 on 2017-12-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrypage',
            old_name='content',
            new_name='body',
        ),
    ]
