# Generated by Django 2.0 on 2017-12-18 14:46

from django.db import migrations
import industry.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_auto_20171215_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=True))))), ('pullout', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock()), ('stat', wagtail.core.blocks.CharBlock())))), ('content', wagtail.core.blocks.TextBlock()), ('snippet', wagtail.snippets.blocks.SnippetChooserBlock(target_model=industry.models.StaticContent)))),
        ),
    ]
