# Generated by Django 2.0.1 on 2018-01-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180116_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='lockup',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header_video',
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
