# Generated by Django 2.0.1 on 2018-01-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrieslandingpage',
            old_name='lockup',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='industrypage',
            old_name='lockup',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='setupguidelandingpage',
            old_name='lockup',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='setupguidepage',
            old_name='lockup',
            new_name='heading',
        ),
    ]
