# Generated by Django 2.0 on 2018-01-02 23:05

from django.db import migrations
import industry.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_auto_20180102_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrypage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('text', wagtailmarkdown.blocks.MarkdownBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=True))))), ('pullout', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock()), ('stat_header', wagtail.core.blocks.CharBlock()), ('stat_text', wagtail.core.blocks.CharBlock())))), ('content', wagtailmarkdown.blocks.MarkdownBlock()), ('snippet', industry.models.IndustrySnippetBlock(target_model=industry.models.StaticContent)))),
        ),
    ]
