# Generated by Django 2.0 on 2018-01-03 00:41

from django.db import migrations, models
import industry.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0006_auto_20180102_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindUsOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='industrypage',
            name='report_problem',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrypage',
            name='sharing_text',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('text', wagtail.core.blocks.CharBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=True))))), ('pullout', wagtail.core.blocks.StructBlock((('text', wagtailmarkdown.blocks.MarkdownBlock()), ('stat_header', wagtail.core.blocks.CharBlock()), ('stat_text', wagtail.core.blocks.CharBlock())))), ('content', wagtailmarkdown.blocks.MarkdownBlock()), ('common_content', industry.models.IndustrySnippetBlock(target_model=industry.models.StaticContent)))),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='text',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
