# Generated by Django 2.0 on 2018-01-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0007_auto_20180103_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrypage',
            name='report_problem',
        ),
        migrations.RemoveField(
            model_name='industrypage',
            name='sharing_text',
        ),
    ]
