# Generated by Django 2.0 on 2018-01-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0008_auto_20180103_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrypage',
            name='report_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_problem', to='industry.StaticContent'),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='sharing_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_text', to='industry.StaticContent'),
        ),
    ]
